// src/pages/index/index.tsx
import React, { PropsWithChildren, useEffect, useState } from "react";
import { View, Icon } from "@tarojs/components";
import { showModal } from "@tarojs/taro";
var Calc = require("../../utils/calc");
import "./index.less";

const Index: React.FC<PropsWithChildren> = () => {
  const [calc, setCalc] = useState<any>({});
  const [tapped, setTapped] = useState<any>({});
  useEffect(() => {
    Calc.reset();
  }, []);

  const showAbout = (e) => {
    showModal({
      title: "关于",
      content:
        "一个简单的计算器 @V1.0，原来的内容已迁移至 https://it-blacklist.github.io",
      showCancel: false,
    });
  };
  const btnClicked = (e) => {
    console.log(e);
    var code = e.target.dataset.op;
    Calc.addOp(code);
    console.log(Calc.getVars());
    setCalc(Calc.getVars());
  };
  const btnTouchStart = (e) => {
    console.log(e);
    var code = e.target.dataset.op;
    var tapped = { [code]: "active" };
    setTapped(tapped);
  };
  const btnTouchEnd = (e) => {
    console.log(e);
    var code = e.target.dataset.op;
    var tapped = {};
    setTapped(tapped);
  };

  return (
    <View className="container">
      <View class="panel-display" style="position: relative;">
        <View>
          <Icon
            id="icon-about"
            type="info"
            size="28"
            color="#aaa"
            onClick={showAbout}
          />
        </View>
        <View id="display-num">{calc.displayNum}</View>
        <View id="display-op">{calc.displayOp}</View>
      </View>
      <View className="panel-btns">
        <View className="btns-rows">
          <View
            id="btn-c"
            className={`btn ${tapped["c"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="c"
          >
            AC
          </View>
          <View
            className={`btn ${tapped["d"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="d"
          >
            DEL
          </View>
          <View
            class={`btn ${tapped["/"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="/"
            style="font-size: 24px;"
          >
            ÷
          </View>
          <View
            className={`btn ${tapped["x"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="x"
          >
            ×
          </View>
        </View>
        <View className="btns-rows">
          <View
            className={`btn ${tapped["7"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="7"
          >
            7
          </View>
          <View
            className={`btn ${tapped["8"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="8"
          >
            8
          </View>
          <View
            className={`btn ${tapped["9"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="9"
          >
            9
          </View>
          <View
            className={`btn ${tapped["-"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="-"
          >
            -
          </View>
        </View>
        <View className="btns-rows">
          <View
            className={`btn ${tapped["4"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="4"
          >
            4
          </View>
          <View
            className={`btn ${tapped["5"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="5"
          >
            5
          </View>
          <View
            className={`btn ${tapped["6"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="6"
          >
            6
          </View>
          <View
            className={`btn ${tapped["+"]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="+"
          >
            +
          </View>
        </View>
        <View id="btns2" className="btns-rows">
          <View id="btns2-left">
            <View className="btns2-left-part">
              <View
                className={`btn ${tapped["1"]}`}
                onClick={btnClicked}
                onTouchstart={btnTouchStart}
                onTouchend={btnTouchEnd}
                data-op="1"
              >
                1
              </View>
              <View
                className={`btn ${tapped["2"]}`}
                onClick={btnClicked}
                onTouchstart={btnTouchStart}
                onTouchend={btnTouchEnd}
                data-op="2"
              >
                2
              </View>
              <View
                className={`"btn ${tapped["3"]}`}
                onClick={btnClicked}
                onTouchstart={btnTouchStart}
                onTouchend={btnTouchEnd}
                data-op="3"
              >
                3
              </View>
            </View>
            <View className="btns2-left-part">
              <View
                className={`btn ${tapped["%"]}`}
                onClick={btnClicked}
                onTouchstart={btnTouchStart}
                onTouchend={btnTouchEnd}
                data-op="%"
              >
                %
              </View>
              <View
                className={`btn ${tapped["0"]}`}
                onClick={btnClicked}
                onTouchstart={btnTouchStart}
                onTouchend={btnTouchEnd}
                data-op="0"
              >
                0
              </View>
              <View
                className={`btn ${tapped["."]}`}
                onClick={btnClicked}
                onTouchstart={btnTouchStart}
                onTouchend={btnTouchEnd}
                data-op="."
              >
                .
              </View>
            </View>
          </View>
          <View
            id="btns2-right"
            className={`btn ${tapped["="]}`}
            onClick={btnClicked}
            onTouchstart={btnTouchStart}
            onTouchend={btnTouchEnd}
            data-op="="
          >
            =
          </View>
        </View>
      </View>
    </View>
  );
};

export default Index;

// src/packages/math-calculator/index/index.vue
<!-- 使用 type="home" 属性设置首页，其他页面不需要设置，默认为page；推荐使用json5，更强大，且允许注释 -->
<route lang="json5">
{
  style: {
    navigationBarTitleText: '数学计算器',
  },
}
</route>
<template>
  <view class="container">
    <view class="panel-display" style="position: relative">
      <view id="display-num">{{ calc.displayNum }}</view>
      <view id="display-op">{{ calc.displayOp }}</view>
    </view>
    <view class="panel-btns">
      <view class="btns-rows">
        <view
          id="btn-c"
          :class="`btn ${tapped.c}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="c"
        >
          AC
        </view>
        <view
          :class="`btn ${tapped.d}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="d"
        >
          DEL
        </view>
        <view
          :class="`btn ${tapped['/']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="/"
          style="font-size: 24px"
        >
          ÷
        </view>
        <view
          :class="`btn ${tapped.x}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="x"
        >
          ×
        </view>
      </view>
      <view class="btns-rows">
        <view
          :class="`btn ${tapped['7']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="7"
        >
          7
        </view>
        <view
          :class="`btn ${tapped['8']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="8"
        >
          8
        </view>
        <view
          :class="`btn ${tapped['9']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="9"
        >
          9
        </view>
        <view
          :class="`btn ${tapped['-']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="-"
        >
          -
        </view>
      </view>
      <view class="btns-rows">
        <view
          :class="`btn ${tapped['4']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="4"
        >
          4
        </view>
        <view
          :class="`btn ${tapped['5']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="5"
        >
          5
        </view>
        <view
          :class="`btn ${tapped['6']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="6"
        >
          6
        </view>
        <view
          :class="`btn ${tapped['+']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="+"
        >
          +
        </view>
      </view>
      <view id="btns2" class="btns-rows">
        <view id="btns2-left">
          <view class="btns2-left-part">
            <view
              class="`btn ${tapped['1']}`"
              @click="btnClicked"
              @touchstart="btnTouchStart"
              @touchend="btnTouchEnd"
              data-op="1"
            >
              1
            </view>
            <view
              :class="`btn ${tapped['2']}`"
              @click="btnClicked"
              @touchstart="btnTouchStart"
              @touchend="btnTouchEnd"
              data-op="2"
            >
              2
            </view>
            <view
              :class="`btn ${tapped['3']}`"
              @click="btnClicked"
              @touchstart="btnTouchStart"
              @touchend="btnTouchEnd"
              data-op="3"
            >
              3
            </view>
          </view>
          <view class="btns2-left-part">
            <view
              :class="`btn ${tapped['%']}`"
              @click="btnClicked"
              @touchstart="btnTouchStart"
              @touchend="btnTouchEnd"
              data-op="%"
            >
              %
            </view>
            <view
              :class="`btn ${tapped['0']}`"
              @click="btnClicked"
              @touchstart="btnTouchStart"
              @touchend="btnTouchEnd"
              data-op="0"
            >
              0
            </view>
            <view
              :class="`btn ${tapped['.']}`"
              @click="btnClicked"
              @touchstart="btnTouchStart"
              @touchend="btnTouchEnd"
              data-op="."
            >
              .
            </view>
          </view>
        </view>
        <view
          id="btns2-right"
          :class="`btn ${tapped['=']}`"
          @click="btnClicked"
          @touchstart="btnTouchStart"
          @touchend="btnTouchEnd"
          data-op="="
        >
          =
        </view>
      </view>
    </view>
  </view>
</template>

<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import Calc from '../utils/calc'
import { onLoad } from '@dcloudio/uni-app'

const calc = ref<any>({})
const tapped = ref<any>({})
onMounted(() => {
  Calc.reset()
})

const btnClicked = (e) => {
  console.log(e)
  const code = e.target.dataset.op
  Calc.addOp(code)
  console.log(Calc.getVars())
  calc.value = Calc.getVars()
}
const btnTouchStart = (e) => {
  console.log(e)
  const code = e.target.dataset.op
  tapped.value = { [code]: 'active' }
}
const btnTouchEnd = (e) => {
  console.log(e)
  const code = e.target.dataset.op
  tapped.value = {}
}

onLoad(() => {
  uni.showShareMenu({})
})
</script>

<style scoped lang="scss">
@import url('./index.scss');
</style>
